import fs from "node:fs";
import vm from "node:vm";
import ts from "typescript";
const code = ts.transpileModule(fs.readFileSync("src/lib/seed.ts", "utf8"), {
  compilerOptions: { module: ts.ModuleKind.CommonJS },
}).outputText;
const exports = {};
vm.runInNewContext(code, {
  exports,
  require: () => ({
    dayOffset: (start, days) => {
      const d = new Date(`${start}T00:00:00Z`);
      d.setUTCDate(d.getUTCDate() + days);
      return d.toISOString().slice(0, 10);
    },
  }),
});
const { preview } = exports;
const quote = (v) => `'${String(v).replaceAll("'", "''")}'`;
const workspace = "10000000-0000-4000-8000-000000000001";
const id = (kind, i) =>
  `${kind}0000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`;
let sql = `-- Generated by npm run db:seed:generate. Re-runnable, does not overwrite existing data.\n-- Real members are bootstrapped separately. Tasks stay Backlog until assigned.\ninsert into public.admin_workspaces(id,name,slug,start_date) values (${quote(workspace)},'HẸN','hen',${quote(preview.startDate)}) on conflict do nothing;\n`;
preview.products.forEach((p, i) => {
  sql += `insert into public.admin_products(id,workspace_id,name,slug,moment,audience,promise,stage,sort_order) values (${[id("2", i), workspace, p.name, p.slug, p.moment, p.audience, p.promise, p.stage].map(quote).join(",")},${i}) on conflict do nothing;\n`;
});
preview.milestones.forEach((m, i) => {
  sql += `insert into public.admin_milestones(id,workspace_id,name,description,start_week,end_week) values (${[id("3", i), workspace, m.name, m.description].map(quote).join(",")},${m.start_week},${m.end_week}) on conflict do nothing;\n`;
});
preview.tasks.forEach((t, i) => {
  sql += `insert into public.admin_tasks(id,workspace_id,code,title,product_id,status,priority,effort,workstream,due_date,definition_of_done,description) values (${[id("4", i), workspace, t.code, t.title, id("2", 0), "backlog", t.priority].map(quote).join(",")},${t.effort},${[t.workstream, t.due_date, t.definition_of_done, `Vai trò dự kiến: ${t.owner}. Phân công thành viên thật trước khi chuyển Ready.`].map(quote).join(",")}) on conflict do nothing;\n`;
});
[
  [7, 6],
  [9, 7],
  [10, 9],
  [12, 11],
  [13, 12],
  [16, 15],
  [19, 13],
  [19, 18],
].forEach(([task, dep]) => {
  sql += `insert into public.admin_task_dependencies(workspace_id,task_id,depends_on_task_id) values (${[workspace, id("4", task), id("4", dep)].map(quote).join(",")}) on conflict do nothing;\n`;
});
fs.writeFileSync("supabase/seed.sql", sql);
